apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- deployment.yaml

replicas:
  - name: vote
    count: 8

images:
  - name: mecsys/vote
    newTag: v4
