apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../base
patchesStrategicMerge:
- deployment.yaml

replicas:
  - name: vote
    count: 4

images:
  - name: mecsys/vote
    newTag: v4

      #commonLabels:
  #  project: instavote
    #  env: staging

commonAnnotations:
  supported-by: "isaacmecchi@gmail.com"

configMapGenerator:
  - name: vote-options
    envs: 
      - options.env
