apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: vote
  namespace: instavote
spec:
  ingressClassName: default
  rules:
  - host: ci.mecsys.com.br
    http:
      paths:
      - backend:
          service:
            name: vote
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
