apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: 3
  template:
    metadata:
      $setElementOrder/containers:
      - name: vote
      containers:
      - image: schoolofdevops/vote:v4
        name: vote
