apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 8

images:
  - name: mecsys/vote
    newTag: v5 

