apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml

replicas:
  - name: vote
    count: 8

images:
  - name: mecsys/vote
    newTag: v5 

namespace: instavote

commonLabels:
  project: instavote
  env: dev

commonAnnotations:
  supported-by: "isaacmecchi@gmail.com" 

configMapGenerator:
  - name: vote-options
    env: options.env 
